/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse20013 {
  id?: number;
  image?: string;
  firstName?: string;
  lastName?: string;
  officePhone?: string;
  pager?: string;
  companyName?: string;
  coordinatorName?: string;
  coordinatorPhone?: string;
  coordinatorEmail?: string;
  address?: string;
  suite?: string;
  city?: string;
  postalCode?: string;
  residentId?: number;
  yearsInPracticeId?: number;
  stateId?: number;
  countryId?: number;
  handednessId?: number;
  innerGloveSizeId?: number;
  outerGloveSizeId?: number;
  gloveTypeId?: number;
  gownSizeId?: number;
  fellow?: number;
  fellowSubspeciality?: string;
  stateTyped?: string;
  doubleGlove?: number;
  outerGloveTypeId?: number;
  notes?: string;
  specialtyId?: number;
  fellowshipTrained?: number;
  billingCoordinatorName?: string;
  billingCoordinatorPhone?: string;
  billingCoordinatorEmail?: string;
  billingCoordinatorId?: number;
  surgicalCoordinatorId?: number;
}
