/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse20034 {
  id?: number;
  text?: string;
  placeholder?: string;
  clusterId?: number;
  questionTypeId?: number;
  active?: number;
  required?: number;
  position?: number;
  options?: string;
  indent?: number;
}
