/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse2003 {
  id?: number;
  cardId?: number;
  doctorId?: number;
  respondentId?: number;
  name?: string;
  createdAt?: string;
  hospitalId?: number;
  parentSnapshotId?: number;
  surgerySnapshot?: number;
  cpt?: string;
  diagnosisCode?: string;
  surgeryTime?: string;
  admissionStatus?: string;
}
