/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse20033 {
  answersBoxId?: number;
  cardId?: number;
  name?: string;
  cardName?: string;
  cpt?: string;
  diagnosisCode?: string;
  doctorId?: number;
  surgeryTime?: string;
  admissionStatus?: string;
  parentCategoryId?: number;
  parentCategoryName?: string;
  specialtyId?: number;
  categoryName?: string;
  specialityName?: string;
  active?: number;
}
