/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Item65 {
  id: number;
  surgeryId: number;
  surgeryStatusId?: number;
  doctorId?: number;
  respondentId?: number;
  note?: string;
  newValue?: string;
  oldValue?: string;
  eventDate?: string;
  vals?: string;
}
