/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Item97 {
  id: number;
  stateId?: number;
  countryId?: number;
  name?: string;
  email?: string;
  address?: string;
  suite?: string;
  city?: string;
  stateTyped?: string;
  postalCode?: string;
}
