/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Item91 {
  id: number;
  name?: string;
  managerName?: string;
  managerPhone?: string;
  managerPager?: string;
  managerEmail?: string;
  address?: string;
  suite?: string;
  city?: string;
  postalCode?: string;
  stateId?: number;
  countryId?: number;
  stateTyped?: string;
  userRole?: string;
  phone?: string;
  pager?: string;
}
