/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Item61 {
  doctorVendorId?: number;
  doctorId: number;
  vendorId: number;
  vendorFosId?: number;
  vendorDataId?: number;
  enabled?: number;
  doctorFosId?: number;
  doctorDataId?: number;
  vendorFosUserEnabled?: number;
  vendorEmail?: string;
  doctorEmail?: string;
  vendorCompany?: string;
  vendorName?: string;
}
