/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Item8 {
  id: number;
  fosUserId?: number;
  suggestingHospitalId?: number;
  questionId?: number;
  answersBoxId?: number;
  reply?: string;
  createdAt: string;
}
