/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Item73 {
  id: number;
  doctorDataId?: number;
  hospitalDataId?: number;
  username: string;
  usernameCanonical: string;
  email: string;
  emailCanonical: string;
  enabled: number;
  salt: string;
  password: string;
  lastLogin?: string;
  locked: number;
  expired: number;
  expiresAt?: string;
  confirmationToken?: string;
  passwordRequestedAt?: string;
  roles: string;
  credentialsExpired: number;
  credentialsExpireAt?: string;
  practiceId?: number;
  activationToken?: string;
  vendorDataId?: number;
  staffOfId?: number;
  utc?: number;
}
