/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Item95 {
  id?: number;
  userId?: number;
  subject: string;
  message: string;
  createdAt: string;
  viewed: number;
  senderId?: number;
  doctorDataId?: number;
  hospitalDataId?: number;
  email?: string;
  doctorName?: string;
  doctorImage?: string;
  hospitalName?: string;
  hospitalEmail?: string;
}
