/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Item55 {
  fosId?: number;
  enabled?: number;
  doctorDataId?: number;
  firstName?: string;
  lastName?: string;
  hospitalDataId?: number;
  name?: string;
  hospitalFosUserEnabled?: number;
  hospitalFosUserId?: number;
  hospitalId?: number;
  doctorId?: number;
  doctorHospitalId?: number;
}
