/**
 * surgipal_dev
 * API
 *
 * OpenAPI spec version: 1.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Item68 {
  id?: number;
  surgeryId: number;
  note?: string;
  newValue?: string;
  oldValue?: string;
  eventDate?: string;
  doctorId?: number;
  doctorEmail?: string;
  doctorImage?: string;
  doctorFirst?: string;
  doctorLast?: string;
  respondentId?: number;
  respondentEmail?: string;
  respondentImage?: string;
  respondentFirst?: string;
  respondentLast?: string;
}
